## CHAPTER 04 - NUMPY BASICS: ARRAYS AND VECTORIZED COMPUTATIONS

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 35.5 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.44 s


## Creating ndarrays

In [6]:
data = np.random.randn(2, 3)

In [7]:
data

array([[-1.52923775,  0.54116954,  0.14874647],
       [ 0.05651498, -0.36006871, -0.70235138]])

In [8]:
data * 10

array([[-15.29237754,   5.41169541,   1.48746466],
       [  0.56514978,  -3.60068706,  -7.0235138 ]])

In [9]:
data + data

array([[-3.05847551,  1.08233908,  0.29749293],
       [ 0.11302996, -0.72013741, -1.40470276]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [12]:
data1 = [6, 7.5, 8, 0, 1]

In [13]:
arr1 = np.array(data1)

In [14]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [16]:
arr2 = np.array(data2)

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int32')

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [25]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [27]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2.dtype

dtype('int32')

In [31]:
arr = np.array([1, 2, 3, 4, 5])

In [32]:
arr.dtype

dtype('int32')

In [33]:
float_arr = arr.astype(np.float64)

In [34]:
float_arr.dtype

dtype('float64')

In [35]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [36]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [38]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [39]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [40]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [41]:
int_array = np.arange(10)

In [42]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [43]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [44]:
empty_uint32 = np.empty(8, dtype='u4')

In [45]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

## Arithmetic with NumPy Arrays

In [47]:
arr = np.array([[1., 2., 3.], [4., 5., 6.,]])

In [48]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [49]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [50]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [52]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [53]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [54]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [56]:
arr2 > arr1

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

In [61]:
arr = np.arange(10)

In [62]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr[5]

5

In [65]:
arr[5:8]

array([5, 6, 7])

In [66]:
arr[5:8] = 12

In [67]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [69]:
arr_slice = arr[5:8]

In [70]:
arr_slice

array([12, 12, 12])

In [71]:
arr_slice[1] = 12345

In [72]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [74]:
arr_slice[:] = 64

In [75]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [81]:
arr_slice2 = arr[5:8].copy()

In [82]:
arr_slice2

array([64, 64, 64])

In [83]:
arr_slice2[:] = 128

In [84]:
arr_slice2

array([128, 128, 128])

In [85]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [86]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [87]:
arr2d[2]

array([7, 8, 9])

In [88]:
arr2d[0, 2]

3

In [94]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [95]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [96]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
old_values = arr3d[0].copy()

In [98]:
arr3d[0] = 42

In [99]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [100]:
arr3d[0] = old_values

In [101]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [102]:
arr3d[1, 0]

array([7, 8, 9])

In [103]:
x = arr3d[1]

In [105]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [106]:
x[0]

array([7, 8, 9])

In [107]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [108]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [109]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
arr2[:2]

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [111]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [113]:
arr2d[:2, 2]

array([3, 6])

In [114]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [115]:
arr2d[:2, 1:] = 0

In [116]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])