# CHAPTER 05 - GETTING STARTED WITH PANDAS

In [169]:
import pandas as pd

In [170]:
from pandas import Series, DataFrame

## Introduction to pandas Data Structures

In [171]:
obj = pd.Series([4, 7, -5, 3])

In [172]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [173]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [174]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [175]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [176]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [177]:
obj2 = pd.Series([4, 7, -5, 3], index=list('dbac'))

In [178]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [179]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [180]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [181]:
obj2['d']

4

In [182]:
obj2['d'] = 6

In [183]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [184]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [185]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [186]:
import numpy as np

In [187]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [188]:
'b' in obj2

True

In [189]:
'e' in obj2

False

In [190]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [191]:
obj3 = pd.Series(sdata)

In [192]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [193]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [194]:
obj4 = pd.Series(sdata, index=states)

In [195]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [196]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [197]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [198]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [199]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [200]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [201]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [202]:
obj4.name = 'population'

In [203]:
obj4.index.name = 'state'

In [204]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [205]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [206]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [207]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [208]:
obj.index

Index(['Bob', 'Steve', 'Jeff', 'Ryan'], dtype='object')

## DataFrame

In [209]:
data = {'state' :   ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year'  :   [2000, 2001, 2002, 2001, 2002, 2003],
        'pop'   :   [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [210]:
frame = pd.DataFrame(data)

In [211]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [212]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [213]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [214]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                            index=['one', 'two', 'three', 'four','five', 'six'])


In [215]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [216]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [217]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [218]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [219]:
frame2['debt'] = 16.5

In [220]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [221]:
frame2['debt']

one      16.5
two      16.5
three    16.5
four     16.5
five     16.5
six      16.5
Name: debt, dtype: float64

In [222]:
frame2['debt'] = np.arange(6.)

In [223]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [224]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [225]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [226]:
frame2['debt'] = val

In [227]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [228]:
frame2['eastern'] = frame2.state == 'Ohio'

In [229]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [230]:
del frame2['eastern']

In [231]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [232]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [233]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [234]:
frame3 = pd.DataFrame(pop)

In [235]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [236]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [237]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [238]:
pdata = {'Ohio'  : frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [239]:
pdata

{'Ohio': 2001    1.7
 2002    3.6
 Name: Ohio, dtype: float64,
 'Nevada': 2001    2.4
 2002    2.9
 Name: Nevada, dtype: float64}

In [240]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [241]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [242]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [243]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## Index Objects

In [244]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [245]:
obj

a    0
b    1
c    2
dtype: int64

In [246]:
index = obj.index

In [247]:
index

Index(['a', 'b', 'c'], dtype='object')

In [248]:
index[1:]

Index(['b', 'c'], dtype='object')

In [249]:
index['1'] = 'd'

TypeError: Index does not support mutable operations

In [82]:
labels = pd.Index(np.arange(3))

In [83]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [84]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [85]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [86]:
obj2.index is labels

True

In [87]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [88]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [89]:
'Ohio' in frame3.columns

True

In [90]:
2003 in frame3.index

False

In [91]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [92]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## Reindexing

In [93]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=[list('dbac')])

In [94]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [95]:
new_index = list('abcde')

In [96]:
obj.reindex([new_index])

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

['a', 'b', 'c', 'd', 'e']

In [97]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [98]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [99]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [100]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [101]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [102]:
frame2 = frame.reindex(list('abcd'))

In [103]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [104]:
states = ['Texas', 'Utah', 'California']

In [105]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [106]:
frame.reindex(list('abcd'), states)

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

## Dropping Entries from an Axis

In [108]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [109]:
states = ['Texas', 'Utah', 'California']

In [110]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [111]:
frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

## Dropping Entries from an Axis

In [112]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [114]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [115]:
new_obj = obj.drop('c')

In [116]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [117]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [118]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [119]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [120]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [121]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [122]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [124]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [125]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [126]:
obj.drop('c', inplace=True)

In [128]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

## Indexing, Selection, and Filtering

In [160]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [161]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [162]:
obj['b']

1.0

In [163]:
obj[1]

1.0

In [164]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [165]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [166]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [167]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [168]:
obj['b' : 'c']

b    1.0
c    2.0
dtype: float64

In [169]:
obj['b' : 'c'] = 5

In [171]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [172]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [173]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [174]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [175]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [176]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [177]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [178]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [179]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [180]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [181]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [182]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [184]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [185]:
data.loc[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [186]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

## Integer Indexes

In [187]:
ser = pd.Series(np.arange(3.))

In [188]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [189]:
ser[-1]

KeyError: -1

In [190]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [191]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [192]:
ser2[-1]

2.0

In [193]:
ser[:1]

0    0.0
dtype: float64

In [194]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [195]:
ser.iloc[:1]

0    0.0
dtype: float64

## Arithmetic and Data Alignment

In [198]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [199]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [200]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [201]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [202]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [203]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)),
                   columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])

In [204]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                   columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [205]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [206]:

df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [207]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [221]:
df1 = pd.DataFrame({'A': [1, 2]})

In [222]:
df2 = pd.DataFrame({'B': [3, 4]})

In [223]:
df1

A
0  1
1  2

In [224]:
df2

B
0  3
1  4

In [225]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [226]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))

In [227]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))

In [233]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [234]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [230]:
df2.loc[1, 'b'] = np.nan

In [231]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [232]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [235]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [236]:
1/ df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [237]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [238]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [82]:
arr = np.arange(12.).reshape((3,4))

In [83]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [84]:
arr[0]

array([0., 1., 2., 3.])

In [85]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [88]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [89]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [90]:
series = frame.iloc[0]

In [92]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [93]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [94]:
series2 = pd.Series(range(3), index=list('bef'))

In [95]:
series2

b    0
e    1
f    2
dtype: int64

In [101]:
series3 = frame['d']

In [102]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [103]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## Function Application and Mapping

In [106]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [107]:
frame

b         d         e
Utah   -0.387729 -0.762081  0.889025
Ohio   -1.024413 -1.507600 -1.075617
Texas  -0.266906  0.325024 -0.912420
Oregon -0.352151  1.517025  1.260007

In [108]:
np.abs(frame)

b         d         e
Utah    0.387729  0.762081  0.889025
Ohio    1.024413  1.507600  1.075617
Texas   0.266906  0.325024  0.912420
Oregon  0.352151  1.517025  1.260007

In [111]:
 f = lambda x: x.max() - x.min()

In [112]:
frame.apply(f)

b    0.757507
d    3.024624
e    2.335625
dtype: float64

In [113]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [114]:
frame.apply(f)

b         d         e
min -1.024413 -1.507600 -1.075617
max -0.266906  1.517025  1.260007

In [115]:
format = lambda x: '%.2f' % x

In [116]:
frame.applymap(format)

b      d      e
Utah    -0.39  -0.76   0.89
Ohio    -1.02  -1.51  -1.08
Texas   -0.27   0.33  -0.91
Oregon  -0.35   1.52   1.26

In [117]:
frame['e'].map(format)

Utah       0.89
Ohio      -1.08
Texas     -0.91
Oregon     1.26
Name: e, dtype: object

## Sorting and Ranking

In [119]:
obj = pd.Series(range(4), index=list('dabc'))

In [120]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [126]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])

In [128]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [129]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [130]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [131]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [132]:
obj = pd.Series([4, 7, -3, 2])

In [133]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [134]:
obj = pd.Series([4, np.nan, 7, -3, 2])

In [136]:
obj

0    4.0
1    NaN
2    7.0
3   -3.0
4    2.0
dtype: float64

In [137]:
obj.sort_values()

3   -3.0
4    2.0
0    4.0
2    7.0
1    NaN
dtype: float64

In [138]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [139]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [140]:
frame = pd.DataFrame({'b' : [4, 7, -3, 2], 'a':[0, 1, 0, 1]})

In [141]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [142]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [143]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [144]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [145]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [146]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [147]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [148]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})

In [149]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [151]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

## Axis Indexes with Duplicate Labels

In [152]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [153]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [154]:
obj.index.is_unique

False

In [155]:
obj['a']

a    0
a    1
dtype: int64

In [156]:
obj['c']

4

In [157]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [158]:
df

0         1         2
a  0.044264  0.529687 -1.398808
a -1.006694  1.193330 -0.066138
b  1.340491 -0.380228  0.763794
b -1.470830 -0.061946  1.441110

In [159]:
df.loc['b']

0         1         2
b  1.340491 -0.380228  0.763794
b -1.470830 -0.061946  1.441110

## Summarizing and Computing Descriptive Statistics

In [160]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                   index=['a', 'b', 'c', 'd'],
                   columns=['one', 'two'])

In [161]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [162]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [163]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [164]:
df.mean(axis='columns')

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [165]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [166]:
df.idxmax()

one    b
two    d
dtype: object

In [167]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [168]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [169]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [170]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

## Correlation and Covariance

In [253]:
# conda install pandas-datareader
import pandas_datareader.data as web

In [254]:
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [255]:
all_data

{'AAPL':                   High         Low        Open       Close       Volume  \
 Date                                                                      
 2015-10-22   28.875000   28.525000   28.582500   28.875000  166616400.0   
 2015-10-23   29.807501   29.082500   29.174999   29.770000  237467600.0   
 2015-10-26   29.532499   28.730000   29.520000   28.820000  265335200.0   
 2015-10-27   29.135000   28.497499   28.850000   28.637501  279537600.0   
 2015-10-28   29.825001   29.014999   29.232500   29.817499  342205600.0   
 ...                ...         ...         ...         ...          ...   
 2020-10-13  125.389999  119.650002  125.269997  121.099998  262330500.0   
 2020-10-14  123.029999  119.620003  121.000000  121.190002  151062300.0   
 2020-10-15  121.199997  118.150002  118.720001  120.709999  112559200.0   
 2020-10-16  121.550003  118.809998  121.279999  119.019997  115393800.0   
 2020-10-19  120.419998  115.660004  119.959999  115.980003  120221600.0   
 
  

In [260]:
price = pd.DataFrame({ticker: data['Adj Close']
                      for ticker, data in all_data.items()})

In [257]:
price

AAPL         IBM        MSFT         GOOG
Date                                                       
2015-10-22   26.683798  115.387383   43.649437   651.789978
2015-10-23   27.510878  115.859840   48.048008   702.000000
2015-10-26   26.632969  115.042992   49.302139   712.780029
2015-10-27   26.464319  110.398384   48.793213   708.489990
2015-10-28   27.554773  112.776749   49.056763   712.950012
...                ...         ...         ...          ...
2020-10-13  121.099998  125.099998  222.860001  1571.680054
2020-10-14  121.190002  125.940002  220.860001  1568.079956
2020-10-15  120.709999  124.889999  219.660004  1559.130005
2020-10-16  119.019997  125.930000  219.660004  1573.010010
2020-10-19  115.980003  125.519997  214.220001  1534.609985

[1257 rows x 4 columns]

In [261]:
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

In [262]:
volume

AAPL         IBM         MSFT     GOOG
Date                                                     
2015-10-22  166616400.0   5583200.0   56637100.0  4071000
2015-10-23  237467600.0   5370400.0  135227100.0  6653900
2015-10-26  265335200.0   3489400.0   64633300.0  2716600
2015-10-27  279537600.0  15008500.0   50999900.0  2245800
2015-10-28  342205600.0   8511400.0   47000800.0  2178900
...                 ...         ...          ...      ...
2020-10-13  262330500.0   5406100.0   28950800.0  1601000
2020-10-14  151062300.0   3730100.0   23451700.0  1931000
2020-10-15  112559200.0   3385300.0   22733100.0  1540000
2020-10-16  115393800.0   4710400.0   26057900.0  1434700
2020-10-19  120221600.0   7380100.0   27591900.0  1606500

[1257 rows x 4 columns]

In [263]:
returns = price.pct_change()

In [264]:
returns

AAPL       IBM      MSFT      GOOG
Date                                              
2015-10-22       NaN       NaN       NaN       NaN
2015-10-23  0.030996  0.004095  0.100770  0.077034
2015-10-26 -0.031911 -0.007050  0.026102  0.015356
2015-10-27 -0.006332 -0.040373 -0.010323 -0.006019
2015-10-28  0.041205  0.021543  0.005401  0.006295
...              ...       ...       ...       ...
2020-10-13 -0.026527 -0.016587  0.006594  0.001612
2020-10-14  0.000743  0.006715 -0.008974 -0.002291
2020-10-15 -0.003961 -0.008337 -0.005433 -0.005708
2020-10-16 -0.014001  0.008327  0.000000  0.008902
2020-10-19 -0.025542 -0.003256 -0.024766 -0.024412

[1257 rows x 4 columns]

In [265]:
returns['MSFT'].corr(returns['IBM'])

0.569102499026641

In [266]:
returns['MSFT'].cov(returns['IBM'])

0.00016057960860297864

In [267]:
returns.MSFT.corr(returns.IBM)

0.569102499026641

In [268]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.495813  0.710281  0.660001
IBM   0.495813  1.000000  0.569102  0.529474
MSFT  0.710281  0.569102  1.000000  0.785733
GOOG  0.660001  0.529474  0.785733  1.000000

In [269]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000357  0.000150  0.000236  0.000207
IBM   0.000150  0.000257  0.000161  0.000141
MSFT  0.000236  0.000161  0.000310  0.000229
GOOG  0.000207  0.000141  0.000229  0.000275

In [270]:
returns.corrwith(returns.IBM)

AAPL    0.495813
IBM     1.000000
MSFT    0.569102
GOOG    0.529474
dtype: float64

In [271]:
returns.corrwith(volume)

AAPL   -0.102028
IBM    -0.065327
MSFT   -0.056903
GOOG   -0.151703
dtype: float64

In [272]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [273]:
uniques = obj.unique()

In [274]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [277]:
obj.value_counts()

a    3
c    3
b    2
d    1
dtype: int64

In [281]:
pd.value_counts(obj.values, sort=False)

d    1
c    3
b    2
a    3
dtype: int64

In [282]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [283]:
mask = obj.isin(['b', 'c'])

In [284]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [285]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [286]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [287]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [288]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [289]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})

In [290]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [291]:
result = data.apply(pd.value_counts).fillna(0)

In [292]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0