# CHAPTER 12 - ADVANCED PANDAS

In [175]:
import pandas as pd
import numpy as np

In [90]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)

In [176]:
pd.unique(values)

array([0, 1], dtype=int64)

In [92]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [93]:
values = pd.Series([0, 1, 0, 0] * 2)

In [94]:
dim = pd.Series(['apple', 'orange'])

In [95]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [96]:
dim

0     apple
1    orange
dtype: object

In [97]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

## CATEGORICAL TYPE IN PANDAS

In [98]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [99]:
N = len(fruits)

In [100]:
df = pd.DataFrame({'fruit' : fruits,
                   'basket_id' : np.arange(N),
                   'count' : np.random.randint(3, 15, size=N),
                   'weight' : np.random.uniform(0, 4, size=N)},
                   columns=['basket_id', 'fruit', 'count', 'weight'])

In [101]:
df

basket_id   fruit  count    weight
0          0   apple     13  3.030344
1          1  orange      3  3.262913
2          2   apple      3  2.576584
3          3   apple      8  1.390424
4          4   apple     12  3.781494
5          5  orange     11  1.175560
6          6   apple     11  0.977926
7          7   apple     12  1.372471

In [102]:
fruit_cat = df['fruit'].astype('category')

In [103]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [104]:
c = fruit_cat.values

In [105]:
type(c)

pandas.core.arrays.categorical.Categorical

In [106]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [107]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [108]:
df['fruit'] = df.fruit.astype('category')

In [109]:
df.fruit

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [110]:
my_categoriews = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [111]:
my_categoriews

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [112]:
categories = ['foo', 'bar', 'baz']

In [113]:
codes = [0, 1, 2, 0, 0, 1]

In [114]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [115]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [116]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)

In [117]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [118]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

## COMPUTATIONS WITH CATEGORICALS 

In [119]:
np.random.seed(12345)

In [120]:
draws = np.random.randn(1000)

In [121]:
draws[:5]

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057])

In [122]:
bins = pd.qcut(draws, 4)

In [123]:
bins

[(-0.684, -0.0101], (-0.0101, 0.63], (-0.684, -0.0101], (-0.684, -0.0101], (0.63, 3.928], ..., (-0.0101, 0.63], (-0.684, -0.0101], (-2.9499999999999997, -0.684], (-0.0101, 0.63], (0.63, 3.928]]
Length: 1000
Categories (4, interval[float64]): [(-2.9499999999999997, -0.684] < (-0.684, -0.0101] < (-0.0101, 0.63] < (0.63, 3.928]]

In [124]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [125]:
bins

['Q2', 'Q3', 'Q2', 'Q2', 'Q4', ..., 'Q3', 'Q2', 'Q1', 'Q3', 'Q4']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [126]:
bins.codes[:10]

array([1, 2, 1, 1, 3, 3, 2, 2, 3, 3], dtype=int8)

In [127]:
bins = pd.Series(bins, name='quartile')

In [128]:
bins

0      Q2
1      Q3
2      Q2
3      Q2
4      Q4
       ..
995    Q3
996    Q2
997    Q1
998    Q3
999    Q4
Name: quartile, Length: 1000, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [129]:
results = (pd.Series(draws)
            .groupby(bins)
            .agg(['count', 'min', 'max'])
            .reset_index())

In [130]:
results

quartile  count       min       max
0       Q1    250 -2.949343 -0.685484
1       Q2    250 -0.683066 -0.010115
2       Q3    250 -0.010032  0.628894
3       Q4    250  0.634238  3.927528

In [131]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [132]:
N = 10000000

In [133]:
draws = pd.Series(np.random.randn(N))

In [134]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [135]:
categories = labels.astype('category')

In [136]:
labels.memory_usage()

80000128

In [137]:
categories.memory_usage()

10000320

In [138]:
%time _ = labels.astype('category')

Wall time: 481 ms


## CATEGORICAL METHODS

In [139]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [140]:
cat_s = s.astype('category')

In [141]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [142]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [143]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [144]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [145]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [146]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [147]:
cat_s.value_counts()

d    2
c    2
b    2
a    2
dtype: int64

In [148]:
cat_s2.value_counts()

d    2
c    2
b    2
a    2
e    0
dtype: int64

In [149]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [150]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [151]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [152]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [153]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [154]:
pd.get_dummies(cat_s2)

a  b  c  d  e
0  1  0  0  0  0
1  0  1  0  0  0
2  0  0  1  0  0
3  0  0  0  1  0
4  1  0  0  0  0
5  0  1  0  0  0
6  0  0  1  0  0
7  0  0  0  1  0

## ADVANCED GROUPBY USE

In [155]:
df = pd.DataFrame({'key': ['a', 'b', 'c'] * 4, 'value': np.arange(12.)})

In [156]:
g = df.groupby('key').value

In [157]:
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [158]:
g.transform(lambda x: x.mean())

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [159]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [160]:
g.transform(lambda x: x * 2)

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
11    22.0
Name: value, dtype: float64

In [161]:
g.transform(lambda x: x.rank(ascending=False))

0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0
Name: value, dtype: float64

In [162]:
def normalize(x):
    return (x - x.mean()) / x.std()

In [163]:
g.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [164]:
g.apply(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [165]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [166]:
normalized = (df['value'] - g.transform('mean')) / g.transform('std')

## GROUPED TIME RESAMPLING

In [167]:
N = 15

In [168]:
times = pd.date_range('2017-05-20 00:00', freq='1min', periods=N)

In [169]:
df = pd.DataFrame({'time': times, 'value': np.arange(N)})

In [170]:
df

time  value
0  2017-05-20 00:00:00      0
1  2017-05-20 00:01:00      1
2  2017-05-20 00:02:00      2
3  2017-05-20 00:03:00      3
4  2017-05-20 00:04:00      4
5  2017-05-20 00:05:00      5
6  2017-05-20 00:06:00      6
7  2017-05-20 00:07:00      7
8  2017-05-20 00:08:00      8
9  2017-05-20 00:09:00      9
10 2017-05-20 00:10:00     10
11 2017-05-20 00:11:00     11
12 2017-05-20 00:12:00     12
13 2017-05-20 00:13:00     13
14 2017-05-20 00:14:00     14

In [171]:
df.set_index('time').resample('5min').count()

value
time                      
2017-05-20 00:00:00      5
2017-05-20 00:05:00      5
2017-05-20 00:10:00      5

In [172]:
df2 = pd.DataFrame({'time' : times.repeat(3),
                    'key'  :  np.tile(['a', 'b', 'c'], N),
                    'value': np.arange(N * 3)})

In [173]:
df2.head()

time key  value
0 2017-05-20 00:00:00   a      0
1 2017-05-20 00:00:00   b      1
2 2017-05-20 00:00:00   c      2
3 2017-05-20 00:01:00   a      3
4 2017-05-20 00:01:00   b      4

In [182]:
time_key = pd.Grouper(key='time', freq='5min')

In [183]:
time_key

TimeGrouper(key='time', freq=<5 * Minutes>, axis=0, sort=True, closed='left', label='left', how='mean', convention='e', origin='start_day')

In [196]:
resampled = (df2.groupby(['key', time_key]).sum())

In [197]:
resampled

value
key time                      
a   2017-05-20 00:00:00     30
    2017-05-20 00:05:00    105
    2017-05-20 00:10:00    180
b   2017-05-20 00:00:00     35
    2017-05-20 00:05:00    110
    2017-05-20 00:10:00    185
c   2017-05-20 00:00:00     40
    2017-05-20 00:05:00    115
    2017-05-20 00:10:00    190

In [199]:
resampled.reset_index()

key                time  value
0   a 2017-05-20 00:00:00     30
1   a 2017-05-20 00:05:00    105
2   a 2017-05-20 00:10:00    180
3   b 2017-05-20 00:00:00     35
4   b 2017-05-20 00:05:00    110
5   b 2017-05-20 00:10:00    185
6   c 2017-05-20 00:00:00     40
7   c 2017-05-20 00:05:00    115
8   c 2017-05-20 00:10:00    190