# CHAPTER 07 - DATA CLEANING AND PREPARATION

## HANDILING MISSING DATA

In [1]:
import pandas as pd
import numpy as np

In [3]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [4]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [5]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [6]:
string_data[0] = None

In [7]:
string_data

0         None
1    artichoke
2          NaN
3      avocado
dtype: object

In [8]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

## FILTERING OUT MISSING DATA

In [9]:
from numpy import nan as NA

In [10]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [11]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [12]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [14]:
data.dropna(inplace=True)

In [15]:
data

0    1.0
2    3.5
4    7.0
dtype: float64

In [16]:
data = pd.DataFrame([[1., 6.5, 3.], [1., NA, NA],[NA, NA, NA], [NA, 6.5, 3.]])

In [17]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [18]:
cleaned = data.dropna()

In [19]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [20]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [21]:
data[4] = NA

In [22]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [23]:
data.dropna(axis=1, how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [24]:
df = pd.DataFrame(np.random.randn(7,3))

In [25]:
df

0         1         2
0 -0.849261  0.150816 -1.992587
1  1.012175 -2.010335 -1.891874
2  0.733418 -0.885510  0.585835
3  1.556497 -0.050829  1.710517
4 -1.800774 -0.929989  0.038919
5 -0.714751  2.011386  0.213072
6  0.768366  1.632289 -0.829719

In [26]:
df.iloc[:4, 1] = NA

In [27]:
df

0         1         2
0 -0.849261       NaN -1.992587
1  1.012175       NaN -1.891874
2  0.733418       NaN  0.585835
3  1.556497       NaN  1.710517
4 -1.800774 -0.929989  0.038919
5 -0.714751  2.011386  0.213072
6  0.768366  1.632289 -0.829719

In [28]:
df.iloc[:2, 2] = NA

In [29]:
df

0         1         2
0 -0.849261       NaN       NaN
1  1.012175       NaN       NaN
2  0.733418       NaN  0.585835
3  1.556497       NaN  1.710517
4 -1.800774 -0.929989  0.038919
5 -0.714751  2.011386  0.213072
6  0.768366  1.632289 -0.829719

In [30]:
df.dropna()

0         1         2
4 -1.800774 -0.929989  0.038919
5 -0.714751  2.011386  0.213072
6  0.768366  1.632289 -0.829719

In [31]:
df.dropna(thresh=2)

0         1         2
2  0.733418       NaN  0.585835
3  1.556497       NaN  1.710517
4 -1.800774 -0.929989  0.038919
5 -0.714751  2.011386  0.213072
6  0.768366  1.632289 -0.829719

## FILLINING IN MISSING DATA

In [32]:
df.fillna(0)

0         1         2
0 -0.849261  0.000000  0.000000
1  1.012175  0.000000  0.000000
2  0.733418  0.000000  0.585835
3  1.556497  0.000000  1.710517
4 -1.800774 -0.929989  0.038919
5 -0.714751  2.011386  0.213072
6  0.768366  1.632289 -0.829719

In [33]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.849261  0.500000  0.000000
1  1.012175  0.500000  0.000000
2  0.733418  0.500000  0.585835
3  1.556497  0.500000  1.710517
4 -1.800774 -0.929989  0.038919
5 -0.714751  2.011386  0.213072
6  0.768366  1.632289 -0.829719

In [34]:
_ = df.fillna(0, inplace=True)

In [35]:
df

0         1         2
0 -0.849261  0.000000  0.000000
1  1.012175  0.000000  0.000000
2  0.733418  0.000000  0.585835
3  1.556497  0.000000  1.710517
4 -1.800774 -0.929989  0.038919
5 -0.714751  2.011386  0.213072
6  0.768366  1.632289 -0.829719

In [36]:
df = pd.DataFrame(np.random.randn(6, 3))

In [37]:
df

0         1         2
0 -1.151199  2.081647  2.336207
1 -0.744824  1.075600  1.984325
2 -0.073457 -0.862827 -0.555314
3 -1.797327 -0.656244 -0.443001
4 -0.431046  0.259705  1.342550
5 -1.006129  0.492110  0.389123

In [38]:
df.iloc[2:, 1] = NA

In [39]:
df

0         1         2
0 -1.151199  2.081647  2.336207
1 -0.744824  1.075600  1.984325
2 -0.073457       NaN -0.555314
3 -1.797327       NaN -0.443001
4 -0.431046       NaN  1.342550
5 -1.006129       NaN  0.389123

In [40]:
df.iloc[4:, 2] = NA

In [41]:
df

0         1         2
0 -1.151199  2.081647  2.336207
1 -0.744824  1.075600  1.984325
2 -0.073457       NaN -0.555314
3 -1.797327       NaN -0.443001
4 -0.431046       NaN       NaN
5 -1.006129       NaN       NaN

In [42]:
df.fillna(method='ffill')

0         1         2
0 -1.151199  2.081647  2.336207
1 -0.744824  1.075600  1.984325
2 -0.073457  1.075600 -0.555314
3 -1.797327  1.075600 -0.443001
4 -0.431046  1.075600 -0.443001
5 -1.006129  1.075600 -0.443001

In [43]:
df.fillna(method='ffill', limit=2)

0         1         2
0 -1.151199  2.081647  2.336207
1 -0.744824  1.075600  1.984325
2 -0.073457  1.075600 -0.555314
3 -1.797327  1.075600 -0.443001
4 -0.431046       NaN -0.443001
5 -1.006129       NaN -0.443001

In [44]:
data = pd.Series([1., NA, 3.5, NA, 7])

In [45]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

## DATA TRANSFORMATION

In [46]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'], 'k2': [1, 1, 2, 3, 3, 4, 4]})

In [47]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [48]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [49]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [50]:
data['v1'] = range(7)

In [51]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [53]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

## TRANSFORMING DATA USING A FUNCTION OR MAPPING

In [89]:
data = pd.DataFrame({'food' : ['bacon', 'pulled pork', 'bacon',
                    'Pastrami', 'corned beef', 'Bacon',
                    'pastramin', 'honey ham', 'nova lox'],
                    'ounces': [4, 3, 12,6, 7.5, 8,3, 5, 6]})

In [90]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6    pastramin     3.0
7    honey ham     5.0
8     nova lox     6.0

In [91]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}

In [92]:
lowercased = data['food'].str.lower()

In [93]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beef
5          bacon
6      pastramin
7      honey ham
8       nova lox
Name: food, dtype: object

In [94]:
data['animal'] = lowercased.map(meat_to_animal)

In [95]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6    pastramin     3.0     NaN
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [96]:
data['food'] = data['food'].map(lambda x: x.lower())

In [97]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6    pastramin     3.0     NaN
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

## REPLACING VALUES

In [105]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [106]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [107]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [108]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [109]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [114]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [110]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [112]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

## RENAMING AXIS INDEXES

In [2]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [3]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [4]:
transform = lambda x: x[:4].upper()

In [5]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [6]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [7]:
data.index = data.index.map(transform)

In [8]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [9]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [10]:
data.rename(index={'OHIO': 'INDIANA'},
            columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [11]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [12]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

## DISCRETIZATION AND BINNING


In [13]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [15]:
bins = [18, 25, 35, 60, 100]

In [16]:
cats = pd.cut(ages, bins)

In [20]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [22]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [23]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [24]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [25]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [26]:
data = np.random.rand(20)

In [27]:
data

array([0.49593127, 0.62091991, 0.1162389 , 0.37735564, 0.48325494,
       0.20727508, 0.13159602, 0.03005813, 0.20090791, 0.86035313,
       0.29261041, 0.9639514 , 0.39576839, 0.92119559, 0.00167377,
       0.7881718 , 0.79076256, 0.30150663, 0.28391014, 0.91376761])

In [28]:
pd.cut(data, 4, precision=2)

[(0.48, 0.72], (0.48, 0.72], (0.00071, 0.24], (0.24, 0.48], (0.48, 0.72], ..., (0.72, 0.96], (0.72, 0.96], (0.24, 0.48], (0.24, 0.48], (0.72, 0.96]]
Length: 20
Categories (4, interval[float64]): [(0.00071, 0.24] < (0.24, 0.48] < (0.48, 0.72] < (0.72, 0.96]]

In [50]:
data = np.random.randn(1000) # Normally distributed

In [54]:
cats = pd.qcut(data, 4) # Cut into quartiles

In [55]:
cats

[(-0.722, -0.0588], (-2.9459999999999997, -0.722], (-2.9459999999999997, -0.722], (0.624, 3.575], (-0.0588, 0.624], ..., (-0.0588, 0.624], (0.624, 3.575], (-0.722, -0.0588], (-0.722, -0.0588], (-2.9459999999999997, -0.722]]
Length: 1000
Categories (4, interval[float64]): [(-2.9459999999999997, -0.722] < (-0.722, -0.0588] < (-0.0588, 0.624] < (0.624, 3.575]]

In [56]:
pd.value_counts(cats)

(0.624, 3.575]                   250
(-0.0588, 0.624]                 250
(-0.722, -0.0588]                250
(-2.9459999999999997, -0.722]    250
dtype: int64

In [57]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.])

[(-1.268, -0.0588], (-1.268, -0.0588], (-1.268, -0.0588], (-0.0588, 1.224], (-0.0588, 1.224], ..., (-0.0588, 1.224], (-0.0588, 1.224], (-1.268, -0.0588], (-1.268, -0.0588], (-1.268, -0.0588]]
Length: 1000
Categories (4, interval[float64]): [(-2.9459999999999997, -1.268] < (-1.268, -0.0588] < (-0.0588, 1.224] < (1.224, 3.575]]

## DETECTING AND FILTERING OUTLIERS

In [58]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [59]:
data.head()

0         1         2         3
0  0.202109  1.236782  1.520823 -0.846037
1  0.676761 -0.756918 -0.663062  1.177522
2 -0.357313  0.249535  0.043073 -0.291982
3  0.577732 -0.858937  1.459789 -1.152796
4  1.196400  0.241429  0.817708  0.796310

In [60]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.005248     0.005331    -0.004608     0.001192
std       0.994474     1.012397     0.994644     1.019812
min      -3.540445    -3.094170    -2.814541    -3.889074
25%      -0.646952    -0.676311    -0.707023    -0.700856
50%      -0.015450    -0.005443     0.002878    -0.018011
75%       0.618142     0.670444     0.663724     0.694915
max       2.855395     3.559625     3.640903     3.462428

In [64]:
col = data[2]

In [67]:
col[np.abs(col) > 3]

218    3.640903
Name: 2, dtype: float64

In [75]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
158  0.001183  2.090686  0.237052 -3.079677
203 -3.540445  0.993737  1.651709  0.871679
218 -0.717400 -0.017134  3.640903 -0.881508
270 -0.113723 -0.008869  0.713327  3.157238
278 -2.066753  3.559625  0.844792  1.237800
506  0.449783  3.280728  1.847332  1.149287
595 -0.422664  0.480521 -0.543730 -3.889074
763 -3.342603  1.211545 -0.223596 -0.603116
780  1.090697 -3.094170 -1.395792  0.398320
958  0.866698 -0.953035 -1.379968  3.462428

In [76]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [81]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.004365     0.004584    -0.005248     0.001541
std       0.991601     1.009426     0.992496     1.014613
min      -3.000000    -3.000000    -2.814541    -3.000000
25%      -0.646952    -0.676311    -0.707023    -0.700856
50%      -0.015450    -0.005443     0.002878    -0.018011
75%       0.618142     0.670444     0.663724     0.694915
max       2.855395     3.000000     3.000000     3.000000

In [83]:
np.sign(data).head()

0    1    2    3
0  1.0  1.0  1.0 -1.0
1  1.0 -1.0 -1.0  1.0
2 -1.0  1.0  1.0 -1.0
3  1.0 -1.0  1.0 -1.0
4  1.0  1.0  1.0  1.0

## PERMUTATION AND RANDOM SAMPLING

In [84]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [85]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [99]:
sampler = np.random.permutation(5)

In [100]:
sampler

array([3, 1, 0, 4, 2])

In [101]:
df.take(sampler)

0   1   2   3
3  12  13  14  15
1   4   5   6   7
0   0   1   2   3
4  16  17  18  19
2   8   9  10  11

In [102]:
df.sample(n=3)

0   1   2   3
4  16  17  18  19
3  12  13  14  15
0   0   1   2   3

In [110]:
choices = pd.Series([7, 7, -1, 6, 4])

In [113]:
choices

0    7
1    7
2   -1
3    6
4    4
dtype: int64

In [108]:
draws = choices.sample(n=10, replace=True)

In [112]:
draws

4    4
4    4
3    6
1    7
2   -1
1    7
4    4
1    7
3    6
4    4
dtype: int64

## COMPUTING INDICATOR/DUMMY VARIABLES

In [115]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})

In [116]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [117]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [128]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [129]:
dummies

key_a  key_b  key_c
0      0      1      0
1      0      1      0
2      1      0      0
3      0      0      1
4      1      0      0
5      0      1      0

In [130]:
df_with_dummy = df[['data1']].join(dummies)

In [131]:
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [132]:
mnames = ['movie_id', 'title', 'genres']

In [138]:
movies = pd.read_table('datasets/movielens/movies.dat',
                        sep='::',
                        header=None,
                        names=mnames,
                        engine='python')

In [139]:
movies

movie_id                               title  \
0            1                    Toy Story (1995)   
1            2                      Jumanji (1995)   
2            3             Grumpier Old Men (1995)   
3            4            Waiting to Exhale (1995)   
4            5  Father of the Bride Part II (1995)   
...        ...                                 ...   
3878      3948             Meet the Parents (2000)   
3879      3949          Requiem for a Dream (2000)   
3880      3950                    Tigerland (2000)   
3881      3951             Two Family House (2000)   
3882      3952               Contender, The (2000)   

                            genres  
0      Animation|Children's|Comedy  
1     Adventure|Children's|Fantasy  
2                   Comedy|Romance  
3                     Comedy|Drama  
4                           Comedy  
...                            ...  
3878                        Comedy  
3879                         Drama  
3880                         Drama  
3881                         Drama  
3882                Drama|Thriller  

[3883 rows x 3 columns]

In [140]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [141]:
all_genres = []

In [142]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [144]:
len(all_genres)

6408

In [145]:
genres = pd.unique(all_genres)

In [146]:
len(genres)

18

In [147]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [148]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [149]:
zero_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [150]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [151]:
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
1           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
2           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
4           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    0.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [152]:
gen = movies.genres[0]

In [153]:
gen

"Animation|Children's|Comedy"

In [155]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [157]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [158]:
dummies

Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  \
0           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
1           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
2           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
4           0.0         0.0     0.0        0.0      0.0      0.0    0.0   
...         ...         ...     ...        ...      ...      ...    ...   
3878        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3879        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3880        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3881        0.0         0.0     0.0        0.0      0.0      0.0    0.0   
3882        0.0         0.0     0.0        0.0      0.0      0.0    0.0   

      Action  Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  \
0        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
1        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
2        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
4        0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
...      ...    ...       ...     ...     ...          ...  ...      ...   
3878     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3879     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3880     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3881     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   
3882     0.0    0.0       0.0     0.0     0.0          0.0  0.0      0.0   

      Mystery  Film-Noir  Western  
0         0.0        0.0      0.0  
1         0.0        0.0      0.0  
2         0.0        0.0      0.0  
3         0.0        0.0      0.0  
4         0.0        0.0      0.0  
...       ...        ...      ...  
3878      0.0        0.0      0.0  
3879      0.0        0.0      0.0  
3880      0.0        0.0      0.0  
3881      0.0        0.0      0.0  
3882      0.0        0.0      0.0  

[3883 rows x 18 columns]

In [ ]:
# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html