## CHAPTER 04 - NUMPY BASICS: ARRAYS AND VECTORIZED COMPUTATIONS

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [4]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 35.5 ms


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.44 s


## Creating ndarrays

In [6]:
data = np.random.randn(2, 3)

In [7]:
data

array([[-1.52923775,  0.54116954,  0.14874647],
       [ 0.05651498, -0.36006871, -0.70235138]])

In [8]:
data * 10

array([[-15.29237754,   5.41169541,   1.48746466],
       [  0.56514978,  -3.60068706,  -7.0235138 ]])

In [9]:
data + data

array([[-3.05847551,  1.08233908,  0.29749293],
       [ 0.11302996, -0.72013741, -1.40470276]])

In [10]:
data.shape

(2, 3)

In [11]:
data.dtype

dtype('float64')

In [12]:
data1 = [6, 7.5, 8, 0, 1]

In [13]:
arr1 = np.array(data1)

In [14]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [16]:
arr2 = np.array(data2)

In [17]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr2.ndim

2

In [19]:
arr2.shape

(2, 4)

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr2.dtype

dtype('int32')

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [24]:
np.empty((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [25]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [27]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2.dtype

dtype('int32')

In [31]:
arr = np.array([1, 2, 3, 4, 5])

In [32]:
arr.dtype

dtype('int32')

In [33]:
float_arr = arr.astype(np.float64)

In [34]:
float_arr.dtype

dtype('float64')

In [35]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [36]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [38]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [39]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [40]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [41]:
int_array = np.arange(10)

In [42]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [43]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [44]:
empty_uint32 = np.empty(8, dtype='u4')

In [45]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

## Arithmetic with NumPy Arrays

In [47]:
arr = np.array([[1., 2., 3.], [4., 5., 6.,]])

In [48]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [49]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [50]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [51]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [52]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [53]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [54]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [56]:
arr2 > arr1

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

In [61]:
arr = np.arange(10)

In [62]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
arr[5]

5

In [65]:
arr[5:8]

array([5, 6, 7])

In [66]:
arr[5:8] = 12

In [67]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [69]:
arr_slice = arr[5:8]

In [70]:
arr_slice

array([12, 12, 12])

In [71]:
arr_slice[1] = 12345

In [72]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [74]:
arr_slice[:] = 64

In [75]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [81]:
arr_slice2 = arr[5:8].copy()

In [82]:
arr_slice2

array([64, 64, 64])

In [83]:
arr_slice2[:] = 128

In [84]:
arr_slice2

array([128, 128, 128])

In [85]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [86]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [87]:
arr2d[2]

array([7, 8, 9])

In [88]:
arr2d[0, 2]

3

In [94]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [95]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [96]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
old_values = arr3d[0].copy()

In [98]:
arr3d[0] = 42

In [99]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [100]:
arr3d[0] = old_values

In [101]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [102]:
arr3d[1, 0]

array([7, 8, 9])

In [103]:
x = arr3d[1]

In [105]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [106]:
x[0]

array([7, 8, 9])

In [107]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [108]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [109]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
arr2[:2]

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [111]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [113]:
arr2d[:2, 2]

array([3, 6])

In [114]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [115]:
arr2d[:2, 1:] = 0

In [116]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Boolean Indexing

In [1]:
import numpy as np

In [2]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [3]:
data = np.random.randn(7, 4)

In [4]:
data

array([[ 1.36004984,  0.73570551, -0.94005028,  1.80339608],
       [-0.95741048,  0.17779146, -1.10941186, -1.28603336],
       [ 2.14516246, -0.28327617,  1.56022515, -1.49396481],
       [ 0.30957078,  0.17470703,  0.44819346, -0.80600091],
       [ 0.38210528, -0.35247047, -0.72906221,  0.63284555],
       [ 0.79666117,  0.69254684,  0.31117056, -1.35881861],
       [-1.09596355, -1.19665207,  0.14610061,  1.30653092]])

In [5]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [6]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [7]:
data[names == 'Bob']

array([[ 1.36004984,  0.73570551, -0.94005028,  1.80339608],
       [ 0.30957078,  0.17470703,  0.44819346, -0.80600091]])

In [9]:
data[names == 'Bob', 2]

array([-0.94005028,  0.44819346])

In [10]:
data[names == 'Bob', 3]

array([ 1.80339608, -0.80600091])

In [11]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [12]:
data[~(names == 'Bob')]

array([[-0.95741048,  0.17779146, -1.10941186, -1.28603336],
       [ 2.14516246, -0.28327617,  1.56022515, -1.49396481],
       [ 0.38210528, -0.35247047, -0.72906221,  0.63284555],
       [ 0.79666117,  0.69254684,  0.31117056, -1.35881861],
       [-1.09596355, -1.19665207,  0.14610061,  1.30653092]])

In [16]:
data[names != 'Bob']

array([[-0.95741048,  0.17779146, -1.10941186, -1.28603336],
       [ 2.14516246, -0.28327617,  1.56022515, -1.49396481],
       [ 0.38210528, -0.35247047, -0.72906221,  0.63284555],
       [ 0.79666117,  0.69254684,  0.31117056, -1.35881861],
       [-1.09596355, -1.19665207,  0.14610061,  1.30653092]])

In [17]:
cond = names == 'Bob'

In [18]:
data[~cond]

array([[-0.95741048,  0.17779146, -1.10941186, -1.28603336],
       [ 2.14516246, -0.28327617,  1.56022515, -1.49396481],
       [ 0.38210528, -0.35247047, -0.72906221,  0.63284555],
       [ 0.79666117,  0.69254684,  0.31117056, -1.35881861],
       [-1.09596355, -1.19665207,  0.14610061,  1.30653092]])

In [20]:
mask = (names == 'Bob') | (names == 'Will')

In [21]:
mask

array([ True, False,  True,  True,  True, False, False])

In [22]:
data[mask]

array([[ 1.36004984,  0.73570551, -0.94005028,  1.80339608],
       [ 2.14516246, -0.28327617,  1.56022515, -1.49396481],
       [ 0.30957078,  0.17470703,  0.44819346, -0.80600091],
       [ 0.38210528, -0.35247047, -0.72906221,  0.63284555]])

In [23]:
data[data < 0] = 0

In [24]:
data

array([[1.36004984, 0.73570551, 0.        , 1.80339608],
       [0.        , 0.17779146, 0.        , 0.        ],
       [2.14516246, 0.        , 1.56022515, 0.        ],
       [0.30957078, 0.17470703, 0.44819346, 0.        ],
       [0.38210528, 0.        , 0.        , 0.63284555],
       [0.79666117, 0.69254684, 0.31117056, 0.        ],
       [0.        , 0.        , 0.14610061, 1.30653092]])

In [25]:
data[names != 'Joe'] = 7

In [26]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.17779146, 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.79666117, 0.69254684, 0.31117056, 0.        ],
       [0.        , 0.        , 0.14610061, 1.30653092]])

## Fancy Indexing

In [5]:
import numpy as np

In [6]:
arr = np.empty((8, 4))

In [7]:
arr

array([[2.33132879e-317, 9.13334860e-312, 3.15506945e-312,
        0.00000000e+000],
       [1.69484279e-319, 3.15506945e-312, 0.00000000e+000,
        9.13353691e-312],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        9.13354004e-312],
       [4.94065646e-324, 6.95257429e-310, 2.02369289e-320,
        4.94065646e-324],
       [6.95257435e-310, 9.88131292e-324, 0.00000000e+000,
        0.00000000e+000],
       [1.77235023e-316, 0.00000000e+000,             nan,
        0.00000000e+000],
       [1.89146896e-307, 1.37961302e-306, 6.23053614e-307,
        1.60218627e-306],
       [6.23061763e-307, 6.23058028e-307, 6.89809565e-307,
        8.34445986e-308]])

In [8]:
for i in range(8):
    arr[i] = i

In [9]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [10]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [11]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [12]:
arr = np.arange(32).reshape((8, 4))

In [13]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [14]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [21]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## Transposing Arrays and Swapping Axes

In [22]:
arr = np.arange(15).reshape((3, 5))

In [23]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [25]:
arr = np.random.randn(6, 3)

In [26]:
arr

array([[-0.60662906, -0.36061508,  0.24628765],
       [ 0.69312278,  0.51474708,  0.38087742],
       [ 0.35769685,  0.61495175, -0.19667967],
       [-0.91746324,  1.79755883, -1.4222359 ],
       [ 1.2578364 ,  0.74981762, -0.62715045],
       [ 1.05536621,  0.53706973,  0.24047084]])

In [27]:
np.dot(arr.T, arr)

array([[ 4.51405408,  0.6562678 ,  0.81401917],
       [ 0.6562678 ,  4.85506156, -2.91135956],
       [ 0.81401917, -2.91135956,  2.71830697]])

In [28]:
arr = np.arange(16).reshape((2, 2, 4))

In [29]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [30]:
arr.transpose(1, 0, 2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [32]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [109]:
array1D = ['0', '1', '2', '3', '4']

In [97]:
array2D = [['00', '01', '02', '03', '04'],
           ['10', '11', '12', '13', '14']]

In [107]:
array3D = [[['000', '010', '020', '030', '040'],
            ['100', '110', '120', '130', '140']],

           [['001', '011', '021', '031', '041'],
            ['101', '111', '121', '131', '141']],
          
           [['002', '012', '022', '032', '042'],
            ['102', '112', '122', '132', '142']]]

In [110]:
array1D = np.array(array1D)

In [99]:
array2D = np.array(array2D)

In [100]:
array3D = np.array(array3D)

In [111]:
array1D

array(['0', '1', '2', '3', '4'], dtype='<U1')

In [101]:
array2D

array([['00', '01', '02', '03', '04'],
       ['10', '11', '12', '13', '14']], dtype='<U2')

In [102]:
array3D

array([[['000', '010', '020', '030', '040'],
        ['100', '110', '120', '130', '140']],

       [['001', '011', '021', '031', '041'],
        ['101', '111', '121', '131', '141']],

       [['002', '012', '022', '032', '042'],
        ['102', '112', '122', '132', '142']]], dtype='<U3')

In [112]:
array1D.T

array(['0', '1', '2', '3', '4'], dtype='<U1')

In [103]:
array2D.T

array([['00', '10'],
       ['01', '11'],
       ['02', '12'],
       ['03', '13'],
       ['04', '14']], dtype='<U2')

In [104]:
array3D.T

array([[['000', '001', '002'],
        ['100', '101', '102']],

       [['010', '011', '012'],
        ['110', '111', '112']],

       [['020', '021', '022'],
        ['120', '121', '122']],

       [['030', '031', '032'],
        ['130', '131', '132']],

       [['040', '041', '042'],
        ['140', '141', '142']]], dtype='<U3')

In [113]:
array1D[0]

'0'

In [128]:
array2D[0,0], array2D[0][0]

('00', '00')

In [129]:
array3D[0][0][0]

'000'

In [130]:
array3D[:2]

[[['000', '010', '020', '030', '040'], ['100', '110', '120', '130', '140']],
 [['001', '011', '021', '031', '041'], ['101', '111', '121', '131', '141']]]

In [131]:
array3D

[[['000', '010', '020', '030', '040'], ['100', '110', '120', '130', '140']],
 [['001', '011', '021', '031', '041'], ['101', '111', '121', '131', '141']],
 [['002', '012', '022', '032', '042'], ['102', '112', '122', '132', '142']]]

In [ ]:
https://www.pythoninformer.com/python-libraries/numpy/index-and-slice/