# CHAPTER 05 - GETTING STARTED WITH PANDAS

In [256]:
import pandas as pd

In [257]:
from pandas import Series, DataFrame

## Introduction to pandas Data Structures

In [258]:
obj = pd.Series([4, 7, -5, 3])

In [259]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [260]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [261]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [262]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [263]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [264]:
obj2 = pd.Series([4, 7, -5, 3], index=list('dbac'))

In [265]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [266]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [267]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [268]:
obj2['d']

4

In [269]:
obj2['d'] = 6

In [270]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [271]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [272]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [273]:
import numpy as np

In [274]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [275]:
'b' in obj2

True

In [276]:
'e' in obj2

False

In [277]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [278]:
obj3 = pd.Series(sdata)

In [279]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [280]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [281]:
obj4 = pd.Series(sdata, index=states)

In [282]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [283]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [284]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [285]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [286]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [287]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [288]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [289]:
obj4.name = 'population'

In [290]:
obj4.index.name = 'state'

In [291]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [292]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [293]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [294]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [295]:
obj.index

Index(['Bob', 'Steve', 'Jeff', 'Ryan'], dtype='object')

## DataFrame

In [296]:
data = {'state' :   ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year'  :   [2000, 2001, 2002, 2001, 2002, 2003],
        'pop'   :   [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [297]:
frame = pd.DataFrame(data)

In [298]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [299]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [300]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [301]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                            index=['one', 'two', 'three', 'four','five', 'six'])


In [302]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [303]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [304]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [305]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [306]:
frame2['debt'] = 16.5

In [307]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [308]:
frame2['debt']

one      16.5
two      16.5
three    16.5
four     16.5
five     16.5
six      16.5
Name: debt, dtype: float64

In [309]:
frame2['debt'] = np.arange(6.)

In [310]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [311]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [312]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [313]:
frame2['debt'] = val

In [314]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [315]:
frame2['eastern'] = frame2.state == 'Ohio'

In [316]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [317]:
del frame2['eastern']

In [318]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [319]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [320]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [321]:
frame3 = pd.DataFrame(pop)

In [322]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [323]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [324]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [325]:
pdata = {'Ohio'  : frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [326]:
pdata

{'Ohio': 2001    1.7
 2002    3.6
 Name: Ohio, dtype: float64,
 'Nevada': 2001    2.4
 2002    2.9
 Name: Nevada, dtype: float64}

In [327]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [328]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [329]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [330]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## Index Objects

In [331]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [332]:
obj

a    0
b    1
c    2
dtype: int64

In [333]:
index = obj.index

In [334]:
index

Index(['a', 'b', 'c'], dtype='object')

In [335]:
index[1:]

Index(['b', 'c'], dtype='object')

In [336]:
index['1'] = 'd'

TypeError: Index does not support mutable operations

In [82]:
labels = pd.Index(np.arange(3))

In [83]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [84]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [85]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [86]:
obj2.index is labels

True

In [87]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [88]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [89]:
'Ohio' in frame3.columns

True

In [90]:
2003 in frame3.index

False

In [91]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [92]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## Reindexing

In [93]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=[list('dbac')])

In [94]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [95]:
new_index = list('abcde')

In [96]:
obj.reindex([new_index])

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

['a', 'b', 'c', 'd', 'e']

In [97]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [98]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [99]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [100]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])

In [101]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [102]:
frame2 = frame.reindex(list('abcd'))

In [103]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [104]:
states = ['Texas', 'Utah', 'California']

In [105]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [106]:
frame.reindex(list('abcd'), states)

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

## Dropping Entries from an Axis

In [108]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [109]:
states = ['Texas', 'Utah', 'California']

In [110]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [111]:
frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

## Dropping Entries from an Axis

In [112]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [114]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [115]:
new_obj = obj.drop('c')

In [116]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [117]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [118]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [119]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [120]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [121]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [122]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [124]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [125]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [126]:
obj.drop('c', inplace=True)

In [128]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

## Indexing, Selection, and Filtering

In [160]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [161]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [162]:
obj['b']

1.0

In [163]:
obj[1]

1.0

In [164]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [165]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [166]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [167]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [168]:
obj['b' : 'c']

b    1.0
c    2.0
dtype: float64

In [169]:
obj['b' : 'c'] = 5

In [171]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [172]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])

In [173]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [174]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [175]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [176]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [177]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [178]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [179]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [180]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [181]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [182]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [184]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [185]:
data.loc[:'Utah', 'two']

Ohio        1
Colorado    5
Utah        9
Name: two, dtype: int32

In [186]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14

## Integer Indexes

In [187]:
ser = pd.Series(np.arange(3.))

In [188]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [189]:
ser[-1]

KeyError: -1

In [190]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [191]:
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [192]:
ser2[-1]

2.0

In [193]:
ser[:1]

0    0.0
dtype: float64

In [194]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [195]:
ser.iloc[:1]

0    0.0
dtype: float64

## Arithmetic and Data Alignment

In [198]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [199]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [200]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [201]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [202]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [203]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)),
                   columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])

In [204]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                   columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [205]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [206]:

df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [207]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [221]:
df1 = pd.DataFrame({'A': [1, 2]})

In [222]:
df2 = pd.DataFrame({'B': [3, 4]})

In [223]:
df1

A
0  1
1  2

In [224]:
df2

B
0  3
1  4

In [225]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [226]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))

In [227]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))

In [233]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [234]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [230]:
df2.loc[1, 'b'] = np.nan

In [231]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [232]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [235]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [236]:
1/ df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [237]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [238]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [82]:
arr = np.arange(12.).reshape((3,4))

In [83]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [84]:
arr[0]

array([0., 1., 2., 3.])

In [85]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [88]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [89]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [90]:
series = frame.iloc[0]

In [92]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [93]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [94]:
series2 = pd.Series(range(3), index=list('bef'))

In [95]:
series2

b    0
e    1
f    2
dtype: int64

In [101]:
series3 = frame['d']

In [102]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [103]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## Function Application and Mapping

In [106]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [107]:
frame

b         d         e
Utah   -0.387729 -0.762081  0.889025
Ohio   -1.024413 -1.507600 -1.075617
Texas  -0.266906  0.325024 -0.912420
Oregon -0.352151  1.517025  1.260007

In [108]:
np.abs(frame)

b         d         e
Utah    0.387729  0.762081  0.889025
Ohio    1.024413  1.507600  1.075617
Texas   0.266906  0.325024  0.912420
Oregon  0.352151  1.517025  1.260007

In [111]:
 f = lambda x: x.max() - x.min()

In [112]:
frame.apply(f)

b    0.757507
d    3.024624
e    2.335625
dtype: float64

In [113]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [114]:
frame.apply(f)

b         d         e
min -1.024413 -1.507600 -1.075617
max -0.266906  1.517025  1.260007

In [115]:
format = lambda x: '%.2f' % x

In [116]:
frame.applymap(format)

b      d      e
Utah    -0.39  -0.76   0.89
Ohio    -1.02  -1.51  -1.08
Texas   -0.27   0.33  -0.91
Oregon  -0.35   1.52   1.26

In [117]:
frame['e'].map(format)

Utah       0.89
Ohio      -1.08
Texas     -0.91
Oregon     1.26
Name: e, dtype: object

## Sorting and Ranking

In [119]:
obj = pd.Series(range(4), index=list('dabc'))

In [120]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [126]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])

In [128]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [129]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [130]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [131]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [132]:
obj = pd.Series([4, 7, -3, 2])

In [133]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [134]:
obj = pd.Series([4, np.nan, 7, -3, 2])

In [136]:
obj

0    4.0
1    NaN
2    7.0
3   -3.0
4    2.0
dtype: float64

In [137]:
obj.sort_values()

3   -3.0
4    2.0
0    4.0
2    7.0
1    NaN
dtype: float64

In [138]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [139]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [140]:
frame = pd.DataFrame({'b' : [4, 7, -3, 2], 'a':[0, 1, 0, 1]})

In [141]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [142]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [143]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [144]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [145]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [146]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [147]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [148]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})

In [149]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [151]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

## Axis Indexes with Duplicate Labels

In [152]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [153]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [154]:
obj.index.is_unique

False

In [155]:
obj['a']

a    0
a    1
dtype: int64

In [156]:
obj['c']

4

In [157]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [158]:
df

0         1         2
a  0.044264  0.529687 -1.398808
a -1.006694  1.193330 -0.066138
b  1.340491 -0.380228  0.763794
b -1.470830 -0.061946  1.441110

In [159]:
df.loc['b']

0         1         2
b  1.340491 -0.380228  0.763794
b -1.470830 -0.061946  1.441110

## Summarizing and Computing Descriptive Statistics

In [160]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                   index=['a', 'b', 'c', 'd'],
                   columns=['one', 'two'])

In [161]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [162]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [163]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [164]:
df.mean(axis='columns')

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [165]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [166]:
df.idxmax()

one    b
two    d
dtype: object

In [167]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [168]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [169]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [170]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

## Correlation and Covariance

In [338]:
# conda install pandas-datareader
import pandas_datareader.data as web

In [339]:
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [341]:
all_data

{'AAPL':                   High         Low        Open       Close       Volume  \
 Date                                                                      
 2015-10-14   27.879999   27.389999   27.822500   27.552500  177849600.0   
 2015-10-15   28.025000   27.622499   27.732500   27.965000  150694000.0   
 2015-10-16   28.000000   27.632500   27.945000   27.760000  156930400.0   
 2015-10-19   27.937500   27.527500   27.700001   27.932501  119036800.0   
 2015-10-20   28.542500   27.705000   27.834999   28.442499  195871200.0   
 ...                ...         ...         ...         ...          ...   
 2020-10-05  116.650002  113.550003  113.910004  116.500000  106243800.0   
 2020-10-06  116.120003  112.250000  115.699997  113.160004  161498200.0   
 2020-10-07  115.550003  114.129997  114.620003  115.080002   96849000.0   
 2020-10-08  116.400002  114.589996  116.250000  114.970001   83477200.0   
 2020-10-09  117.000000  114.919998  115.279999  116.970001   99893400.0   
 
  

In [342]:
price = pd.DataFrame({ticker: data['Adj Close']
                      for ticker, data in all_data.items()})

In [343]:
price

AAPL         IBM        MSFT         GOOG
Date                                                       
2015-10-14   25.461657  120.128113   42.422577   651.159973
2015-10-15   25.842854  120.192162   42.722469   661.739990
2015-10-16   25.653408  120.432404   43.176865   662.200012
2015-10-19   25.812820  119.495476   43.276833   666.099976
2015-10-20   26.284117  112.624611   43.413151   650.280029
...                ...         ...         ...          ...
2020-10-05  116.500000  122.010002  210.380005  1486.020020
2020-10-06  113.160004  121.970001  205.910004  1453.439941
2020-10-07  115.080002  124.070000  209.830002  1460.290039
2020-10-08  114.970001  131.490005  210.580002  1485.930054
2020-10-09  116.970001  127.790001  215.809998  1515.219971

[1257 rows x 4 columns]