# CHAPTER 12 - ADVANCED PANDAS

In [11]:
import pandas as pd
import numpy as np

In [12]:
values = pd.Series(['apple', 'orange', 'apple', 'apple'] * 2)

In [13]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [14]:
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [15]:
values = pd.Series([0, 1, 0, 0] * 2)

In [16]:
dim = pd.Series(['apple', 'orange'])

In [17]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [18]:
dim

0     apple
1    orange
dtype: object

In [19]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

## CATEGORICAL TYPE IN PANDAS

In [20]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [21]:
N = len(fruits)

In [22]:
df = pd.DataFrame({'fruit' : fruits,
                   'basket_id' : np.arange(N),
                   'count' : np.random.randint(3, 15, size=N),
                   'weight' : np.random.uniform(0, 4, size=N)},
                   columns=['basket_id', 'fruit', 'count', 'weight'])

In [23]:
df

basket_id   fruit  count    weight
0          0   apple     12  1.751715
1          1  orange      9  1.602366
2          2   apple     13  3.166120
3          3   apple     14  2.025721
4          4   apple     10  1.053195
5          5  orange     14  3.904010
6          6   apple     10  0.415916
7          7   apple     12  0.476242

In [24]:
fruit_cat = df['fruit'].astype('category')

In [25]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [26]:
c = fruit_cat.values

In [27]:
type(c)

pandas.core.arrays.categorical.Categorical

In [28]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [29]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [31]:
df['fruit'] = df.fruit.astype('category')

In [33]:
df.fruit

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [35]:
my_categoriews = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [36]:
my_categoriews

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [37]:
categories = ['foo', 'bar', 'baz']

In [38]:
codes = [0, 1, 2, 0, 0, 1]

In [39]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [40]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [41]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)

In [42]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [43]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

## COMPUTATIONS WITH CATEGORICALS 

In [45]:
np.random.seed(12345)

In [46]:
draws = np.random.randn(1000)

In [47]:
draws[:5]

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057])

In [48]:
bins = pd.qcut(draws, 4)

In [49]:
bins

[(-0.684, -0.0101], (-0.0101, 0.63], (-0.684, -0.0101], (-0.684, -0.0101], (0.63, 3.928], ..., (-0.0101, 0.63], (-0.684, -0.0101], (-2.9499999999999997, -0.684], (-0.0101, 0.63], (0.63, 3.928]]
Length: 1000
Categories (4, interval[float64]): [(-2.9499999999999997, -0.684] < (-0.684, -0.0101] < (-0.0101, 0.63] < (0.63, 3.928]]

In [53]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [54]:
bins

['Q2', 'Q3', 'Q2', 'Q2', 'Q4', ..., 'Q3', 'Q2', 'Q1', 'Q3', 'Q4']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [55]:
bins.codes[:10]

array([1, 2, 1, 1, 3, 3, 2, 2, 3, 3], dtype=int8)

In [56]:
bins = pd.Series(bins, name='quartile')

In [57]:
bins

0      Q2
1      Q3
2      Q2
3      Q2
4      Q4
       ..
995    Q3
996    Q2
997    Q1
998    Q3
999    Q4
Name: quartile, Length: 1000, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [58]:
results = (pd.Series(draws)
            .groupby(bins)
            .agg(['count', 'min', 'max'])
            .reset_index())

In [59]:
results

quartile  count       min       max
0       Q1    250 -2.949343 -0.685484
1       Q2    250 -0.683066 -0.010115
2       Q3    250 -0.010032  0.628894
3       Q4    250  0.634238  3.927528

In [60]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [61]:
N = 10000000

In [62]:
draws = pd.Series(np.random.randn(N))

In [63]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [64]:
categories = labels.astype('category')

In [72]:
labels.memory_usage()

80000128

In [73]:
categories.memory_usage()

10000320

In [74]:
%time _ = labels.astype('category')

Wall time: 537 ms


## CATEGORICAL METHODS

In [76]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [77]:
cat_s = s.astype('category')

In [78]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [79]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [80]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [81]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [82]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [83]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [84]:
cat_s.value_counts()

d    2
c    2
b    2
a    2
dtype: int64

In [85]:
cat_s2.value_counts()

d    2
c    2
b    2
a    2
e    0
dtype: int64

In [86]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [87]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [88]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [89]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [90]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [91]:
pd.get_dummies(cat_s2)

a  b  c  d  e
0  1  0  0  0  0
1  0  1  0  0  0
2  0  0  1  0  0
3  0  0  0  1  0
4  1  0  0  0  0
5  0  1  0  0  0
6  0  0  1  0  0
7  0  0  0  1  0

## ADVANCED GROUPBY USE

In [93]:
df = pd.DataFrame({'key': ['a', 'b', 'c'] * 4, 'value': np.arange(12.)})

In [94]:
g = df.groupby('key').value

In [95]:
g.mean()

key
a    4.5
b    5.5
c    6.5
Name: value, dtype: float64

In [96]:
g.transform(lambda x: x.mean())

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [97]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [98]:
g.transform(lambda x: x * 2)

0      0.0
1      2.0
2      4.0
3      6.0
4      8.0
5     10.0
6     12.0
7     14.0
8     16.0
9     18.0
10    20.0
11    22.0
Name: value, dtype: float64

In [99]:
g.transform(lambda x: x.rank(ascending=False))

0     4.0
1     4.0
2     4.0
3     3.0
4     3.0
5     3.0
6     2.0
7     2.0
8     2.0
9     1.0
10    1.0
11    1.0
Name: value, dtype: float64

In [100]:
def normalize(x):
    return (x - x.mean()) / x.std()

In [101]:
g.transform(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [102]:
g.apply(normalize)

0    -1.161895
1    -1.161895
2    -1.161895
3    -0.387298
4    -0.387298
5    -0.387298
6     0.387298
7     0.387298
8     0.387298
9     1.161895
10    1.161895
11    1.161895
Name: value, dtype: float64

In [103]:
g.transform('mean')

0     4.5
1     5.5
2     6.5
3     4.5
4     5.5
5     6.5
6     4.5
7     5.5
8     6.5
9     4.5
10    5.5
11    6.5
Name: value, dtype: float64

In [104]:
normalized = (df['value'] - g.transform('mean')) / g.transform('std')

## GROUPED TIME RESAMPLING

In [106]:
N = 15

In [107]:
times = pd.date_range('2017-05-20 00:00', freq='1min', periods=N)

In [108]:
df = pd.DataFrame({'time': times, 'value': np.arange(N)})

In [109]:
df

time  value
0  2017-05-20 00:00:00      0
1  2017-05-20 00:01:00      1
2  2017-05-20 00:02:00      2
3  2017-05-20 00:03:00      3
4  2017-05-20 00:04:00      4
5  2017-05-20 00:05:00      5
6  2017-05-20 00:06:00      6
7  2017-05-20 00:07:00      7
8  2017-05-20 00:08:00      8
9  2017-05-20 00:09:00      9
10 2017-05-20 00:10:00     10
11 2017-05-20 00:11:00     11
12 2017-05-20 00:12:00     12
13 2017-05-20 00:13:00     13
14 2017-05-20 00:14:00     14

In [112]:
df.set_index('time').resample('5min').count()

value
time                      
2017-05-20 00:00:00      5
2017-05-20 00:05:00      5
2017-05-20 00:10:00      5